### ISSUE TITLE
Crash after press NUM 5

### ISSUE THREAD

**Issue by DustyDrew** [Hyjarion/Witcher3-MP#1]
I do everything , as saying in manual. But when I press num 5 in game , game gonna crash. Server window saying bout my connection actually. Some ideas?

**Comment by Hyjarion** [comment]
Do you have the required game version?

**Comment by DustyDrew** [comment]
Version 1.21. No DLC. Win10 x64. 

Crash log:
Crash reason: EXCEPTION_ACCESS_VIOLATION (3221225477), Error reading location 0x561187fb

Crashed Thread:

Thread ID: 14224

callstack:
<Unknown Symbol>() + 0x0 - <Unknown File>(0)
<Unknown Symbol>() + 0x0 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

Debug Information
================================================================

Commandline: "D:\The Witcher 3 Wild Hunt\bin\x64\witcher3.exe"  

Thread ID: 2556

callstack:
Scaleform::Render::Matrix2x4<float>::Prepend() + 0xc387a - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xef2f7 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x11d6 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x424dd - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x162f - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x18fc - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x23d838 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 8720

callstack:
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 15588

callstack:
CreateDispatcherQueueController() + 0x11f59 - <Unknown File>(0)
CreateDispatcherQueueController() + 0x116e1 - <Unknown File>(0)
CreateDispatcherQueueController() + 0x10964 - <Unknown File>(0)
CreateDispatcherQueueController() + 0x140e4 - <Unknown File>(0)
CreateDispatcherQueueController() + 0x10e48 - <Unknown File>(0)
CoreUICreateEx() + 0x1a15 - <Unknown File>(0)
CoreUICreateEx() + 0x89b - <Unknown File>(0)
Ordinal2604() + 0x3a7a - <Unknown File>(0)
DllGetActivationFactory() + 0x4109 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 10764

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xb95437 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4a80 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x245ee7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24608e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 15324

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4a80 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x245ee7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24608e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 5944

callstack:
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 9768

callstack:
DllUnregisterServer() + 0x45ad - <Unknown File>(0)
DllUnregisterServer() + 0x48a6 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 1820

callstack:
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 4332

callstack:
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 15264

callstack:
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 11532

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4a80 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x245ee7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24608e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 13208

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4a80 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x245ee7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24608e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 1740

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4a80 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x245ee7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24608e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 11360

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4a80 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x245ee7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24608e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 9112

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4a80 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x245ee7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24608e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 18172

callstack:
<Unknown Symbol>() + 0x0 - <Unknown File>(0)
<Unknown Symbol>() + 0x0 - <Unknown File>(0)
<Unknown Symbol>() + 0x0 - <Unknown File>(0)
<Unknown Symbol>() + 0x0 - <Unknown File>(0)
configthreadlocale() + 0x92 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 6240

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xbdbfc - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4a80 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x245ee7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24608e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 6252

callstack:
Scaleform::System::~System() + 0x7f12f7 - <Unknown File>(0)
Scaleform::System::~System() + 0x7f13b0 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 8620

callstack:
Scaleform::System::~System() + 0x7f12f7 - <Unknown File>(0)
Scaleform::System::~System() + 0x7f13b0 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 9728

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xbe2adf - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xbe28bb - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xbee22d - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xbed51c - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x58ad - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x9b291 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xc1e811 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xc1bb31 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xbc4bc5 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x27972 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x276d2 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4a80 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x245ee7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24608e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 6800

callstack:
messageBusRemoveObserver() + 0x1a2c1 - <Unknown File>(0)
messageBusRemoveObserver() + 0x3e076 - <Unknown File>(0)
messageBusRemoveObserver() + 0x294170 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 4964

callstack:
messageBusRemoveObserver() + 0x3b0b6 - <Unknown File>(0)
messageBusRemoveObserver() + 0x1a2e4 - <Unknown File>(0)
messageBusRemoveObserver() + 0x3e076 - <Unknown File>(0)
messageBusRemoveObserver() + 0x294170 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 16664

callstack:
OpenAdapter12() + 0x6ee461 - <Unknown File>(0)
OpenAdapter12() + 0x6ee65a - <Unknown File>(0)
NVAPI_DirectMethods() + 0x12e63 - <Unknown File>(0)
NVAPI_DirectMethods() + 0x1b60f - <Unknown File>(0)
OpenAdapter12() + 0x65cbfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 17704

callstack:
NVAPI_Thunk() + 0x211e3f - <Unknown File>(0)
OpenAdapter12() + 0x65cbfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 9828

callstack:
NVAPI_Thunk() + 0x211e3f - <Unknown File>(0)
OpenAdapter12() + 0x65cbfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 16228

callstack:
NVAPI_Thunk() + 0x211e3f - <Unknown File>(0)
OpenAdapter12() + 0x65cbfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 17572

callstack:
NVAPI_Thunk() + 0x211e3f - <Unknown File>(0)
OpenAdapter12() + 0x65cbfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 10680

callstack:
NVAPI_Thunk() + 0x211e3f - <Unknown File>(0)
OpenAdapter12() + 0x65cbfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 5000

callstack:
NVAPI_Thunk() + 0x211e3f - <Unknown File>(0)
OpenAdapter12() + 0x65cbfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 11276

callstack:
NVAPI_Thunk() + 0x211e3f - <Unknown File>(0)
OpenAdapter12() + 0x65cbfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 8668

callstack:
NVAPI_Thunk() + 0x211e3f - <Unknown File>(0)
OpenAdapter12() + 0x65cbfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Game

Last opened world: kaer_morhen.w2w

================================================================

Game

Last opened world: kaer_morhen.w2w

**Comment by Hyjarion** [comment]
You need 1.31 https://www.nexusmods.com/witcher3/mods/3374

**Comment by DustyDrew** [comment]
After replace files from downloaded archive same crash
https://imgur.com/a/Im9Lcnf - Screen from game & server window

Crashlog:

Crash reason: EXCEPTION_ACCESS_VIOLATION (3221225477), Error reading location 0x561187fb

Crashed Thread:

Thread ID: 16460

callstack:
<Unknown Symbol>() + 0x0 - <Unknown File>(0)
<Unknown Symbol>() + 0x0 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

Debug Information
================================================================

Commandline: "D:\The Witcher 3 Wild Hunt\bin\x64\witcher3.exe"  

Thread ID: 13080

callstack:
Scaleform::Render::Matrix2x4<float>::Prepend() + 0xc387a - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xef2f7 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x11d6 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x424dd - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x162f - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0x18fc - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x23d838 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 4544

callstack:
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 8720

callstack:
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 2120

callstack:
CreateDispatcherQueueController() + 0x11f59 - <Unknown File>(0)
CreateDispatcherQueueController() + 0x116e1 - <Unknown File>(0)
CreateDispatcherQueueController() + 0x10964 - <Unknown File>(0)
CreateDispatcherQueueController() + 0x140e4 - <Unknown File>(0)
CreateDispatcherQueueController() + 0x10e48 - <Unknown File>(0)
CoreUICreateEx() + 0x1a15 - <Unknown File>(0)
CoreUICreateEx() + 0x89b - <Unknown File>(0)
Ordinal2604() + 0x3a7a - <Unknown File>(0)
DllGetActivationFactory() + 0x4109 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 1368

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xb95437 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4a80 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x245ee7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24608e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 2080

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4a80 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x245ee7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24608e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 14740

callstack:
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 16964

callstack:
DllUnregisterServer() + 0x45ad - <Unknown File>(0)
DllUnregisterServer() + 0x48a6 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 15772

callstack:
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 14788

callstack:
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 14712

callstack:
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 14692

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4a80 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x245ee7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24608e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 14696

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4a80 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x245ee7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24608e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 14688

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4a80 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x245ee7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24608e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 14704

callstack:
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x8b242 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xbd13b7 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xbcd929 - <Unknown File>(0)
Scaleform::System::~System() + 0x3e18b1 - <Unknown File>(0)
Scaleform::System::~System() + 0x410594 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4a80 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x245ee7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24608e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 18292

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4a80 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x245ee7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24608e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 17220

callstack:
<Unknown Symbol>() + 0x0 - <Unknown File>(0)
<Unknown Symbol>() + 0x0 - <Unknown File>(0)
<Unknown Symbol>() + 0x0 - <Unknown File>(0)
<Unknown Symbol>() + 0x0 - <Unknown File>(0)
configthreadlocale() + 0x92 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 12392

callstack:
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xbdbfc - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4a80 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x245ee7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24608e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 2872

callstack:
Scaleform::System::~System() + 0x7f12f7 - <Unknown File>(0)
Scaleform::System::~System() + 0x7f13b0 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 4620

callstack:
Scaleform::System::~System() + 0x7f12f7 - <Unknown File>(0)
Scaleform::System::~System() + 0x7f13b0 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 16276

callstack:
CreateDirect3D11SurfaceFromDXGISurface() + 0x13268 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xcdc8 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xbc9e3d - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x9a8ba - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xc1e2d0 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xc1b6c9 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xbc4bc5 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x27972 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x276d2 - <Unknown File>(0)
Scaleform::Render::Matrix4x4<float>::SetIdentity() + 0xba4a80 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x245ee7 - <Unknown File>(0)
Scaleform::Render::Matrix2x4<float>::Prepend() + 0x24608e - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 16308

callstack:
messageBusRemoveObserver() + 0x1a2c1 - <Unknown File>(0)
messageBusRemoveObserver() + 0x3e076 - <Unknown File>(0)
messageBusRemoveObserver() + 0x294170 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 9428

callstack:
messageBusRemoveObserver() + 0x3b0b6 - <Unknown File>(0)
messageBusRemoveObserver() + 0x1a2e4 - <Unknown File>(0)
messageBusRemoveObserver() + 0x3e076 - <Unknown File>(0)
messageBusRemoveObserver() + 0x294170 - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 1692

callstack:
OpenAdapter12() + 0x6ee461 - <Unknown File>(0)
OpenAdapter12() + 0x6ee65a - <Unknown File>(0)
NVAPI_DirectMethods() + 0x12e63 - <Unknown File>(0)
NVAPI_DirectMethods() + 0x1b60f - <Unknown File>(0)
OpenAdapter12() + 0x65cbfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 13208

callstack:
NVAPI_Thunk() + 0x211e3f - <Unknown File>(0)
OpenAdapter12() + 0x65cbfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 18232

callstack:
NVAPI_Thunk() + 0x211e3f - <Unknown File>(0)
OpenAdapter12() + 0x65cbfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 17540

callstack:
NVAPI_Thunk() + 0x211e3f - <Unknown File>(0)
OpenAdapter12() + 0x65cbfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 12460

callstack:
NVAPI_Thunk() + 0x211e3f - <Unknown File>(0)
OpenAdapter12() + 0x65cbfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 13736

callstack:
NVAPI_Thunk() + 0x211e3f - <Unknown File>(0)
OpenAdapter12() + 0x65cbfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 4880

callstack:
NVAPI_Thunk() + 0x211e3f - <Unknown File>(0)
OpenAdapter12() + 0x65cbfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Thread ID: 9604

callstack:
NVAPI_Thunk() + 0x211e3f - <Unknown File>(0)
OpenAdapter12() + 0x65cbfe - <Unknown File>(0)
BaseThreadInitThunk() + 0x14 - <Unknown File>(0)
RtlUserThreadStart() + 0x21 - <Unknown File>(0)

================================================================

Game

Last opened world: kaer_morhen.w2w

================================================================

Game

Last opened world: kaer_morhen.w2w

================================================================
