### ISSUE TITLE
Hello. Game crash 4.04

### ISSUE THREAD

**Issue by werasik2aa** [Hyjarion/Witcher3-MP#3]
Can i ask question. 
This mod will be updated to Witcher3 Wild Hunt3 4.0.4 version next-gen? Or developping of this mod abandoned on some days, or forever?

**Comment by BeefSpogdar** [comment]
heyt  i lknow this is old but was the mod working for you? cant find anything on how to actually install unless i missed it

**Comment by DustyDrew** [comment]
After so many time......i still can not start this mod correct. I trying play on different versions , and have no result.....

**Comment by werasik2aa** [comment]
I don't want to wait when this mod continues develop so: 
https://github.com/werasik2aa/Witcher3-Multiplayer
